server:
  service:
    type: LoadBalancer
    servicePort: 80
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip

alertmanager:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: true


# Intalação Básica:
# helm install prometheus oci://ghcr.io/prometheus-community/charts/prometheus --namespace monitoramento --create-namespace

# Instalação com Values
#  helm upgrade prometheus oci://ghcr.io/prometheus-community/charts/prometheus --values values.yaml --namespace monitoramento --install  --create-namespace